apiVersion: v2
name: sd-regulatory-compliance
description: "BIAN Service Domain: Regulatory Compliance (Manage pattern, Risk and Compliance)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Risk and Compliance"
  bian/business-domain: "Compliance"
  bian/asset-type: "Compliance Requirement"
  bian/control-record: "Compliance Requirement Management Plan"
